name: CI/CD Pipeline

# Wokflow trigger: On push events on main branch
on:
  push:
    branches: [ "main" ]

jobs:
  # Each job run in an isolated environment
  compile:
    # Where your job would run. ubuntu-latest: shared runner provided by GitHub
    runs-on: ubuntu-latest

    steps:
    - # actions = create a local copy of the code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

   
